### ISSUE TITLE
Unreproducible

### ISSUE THREAD

**Issue by O-OoOvO** [NegVSR/NegVSR#1]
what did I do：
1. 
```
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch
pip install mmedit==0.15.1

pip install openmim
mim install mmcv-full  # also try version 1.7.2, 1.7.0 1.6.2,  doesn't work. 
```
2. 
clone [RealBasicVSR](https://github.com/ckkelvinchan/RealBasicVSR) and NegVSR repo. copy config from RealBasicVSR to NegVSR repo.
3. Replace the basicvsr_net.py 
The result :
```
1. 
from mmedit.models.backbones.utils import build_norm_layer
ModuleNotFoundError: No module named 'mmedit.models.backbones.utils'

2.
2024-01-10 01:56:04,390 - mmedit - INFO - load checkpoint from torchvision path: torchvision://vgg19
load checkpoint from local path: weights/pretrain_wNegVSR_100000itr_finetune_wNegVSR_150000itr.pth
The model and loaded state dict do not match exactly
unexpected key in source state_dict: generator.basicvsr.backward_resblocks_layer1.main.0.weight, generator.basicvsr.backward_resblocks_layer1.main.0.bias, generator.basicvsr.backward_resblocks_layer1.main.2.0.conv1.weight,
3.

```
Q:
1. I really want to know if the code of this repo is **incomplete**? If you reference some files from other repositories, can you provide a complete version of the code?
2. What exactly does "Following [RealBasicVSR](https://github.com/ckkelvinchan/RealBasicVSR)" mean?
3. Which version of mmcv-full is compatible with this project? Can you give the exact name and version of the dependent packages?
I am not a CV professional, please provide as detailed and simple a user manual as possible. Thanks a loooooooooooooooooooot!

**Comment by NegVSR** [comment]
A1&2: Our work is based on the RealBasicVSR, already the complete code (may place some more extraneous import to cause the error report, has been updated). Once you can run RealBasicVSR inference code you can run ours, the premise is that you need to replace our basicvsr_net.py and weights file.
A3: We suggest you use our recommended version of mmedit (0.16.1 is also fine).

**Comment by NegVSR** [comment]
If you still find it difficult to run, we suggest checking out more questions related to mmcv

**Comment by O-OoOvO** [comment]
Thank you for the recent update to the code. It has enabled me to effectively utilize the project for image processing. During my usage, I observed that ~35GB of GPU memory is required to upscale a 1080p photo to 4K resolution. I would like to point out that the model seems to struggle with processing large areas of solid-color backgrounds, a feature quite prevalent in anime. I am eagerly anticipating further advancements in your work.🥹
